import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";

const archivio = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={archivio.className}>{children}</body>
    </html>
  );
}
